vim.g.maplocalleader = " "
require "config.lazy"
-- require "plugins.plugins"
-- require "config.lsp"

-- require "config.add_diagnostics"
require "config.colorscheme"
-- require "config.comment"
-- require "config.indentline"
require "config.keys"
-- require "config.leap"
-- require "config.lualine"
-- require "config.nvim-tree"
require "config.options"
-- require "config.telescope"
-- require "config.toggleterm"
-- require "config.treesitter"
-- require "config.whichkey"
-- require "config.autocommands"
-- require "config.autocorrect"

-- require "config.cmp"
