return {
	{ 'williamboman/mason.nvim', config = function() require('mason').setup {} end },
	{ 'williamboman/mason-lspconfig.nvim'},
	{ 'neovim/nvim-lspconfig'},
	{ 'hrsh7th/nvim-cmp'},
	{ 'hrsh7th/cmp-nvim-lsp'},
	{ 'hrsh7th/cmp-nvim-lua' },
	{ 'hrsh7th/cmp-buffer' },
	{ 'hrsh7th/cmp-path' },
	{ 'hrsh7th/cmp-cmdline' },
	{ 'hrsh7th/vim-vsnip' },
	{ 'hrsh7th/cmp-vsnip' },
	{ 'hrsh7th/vim-vsnip-integ' },
	{ 'f3fora/cmp-spell'},
	{ 'hrsh7th/cmp-calc' },
	{ 'hrsh7th/cmp-emoji' },
	{ 'rafamadriz/friendly-snippets' },
	{ 'simrat39/rust-tools.nvim'},
}
